tp5pp: main.cpp \
		./headers/public_or_private.hpp \
		./headers/complex.hpp \
		./headers/X.hpp \
		./headers/Y.hpp \
		./headers/D.hpp \
		./headers/2D_array.hpp \
		./headers/AB.hpp \
		./headers/Sess.hpp \
		./headers/TU.hpp
	g++ -g ./main.cpp \
		./src/public_or_private.cpp \
		./src/complex.cpp \
		./src/X.cpp \
		./src/Y.cpp \
		./src/D.cpp \
		./src/2D_array.cpp \
		./src/AB.cpp \
		./src/Sess.cpp \
		./src/TU.cpp \
		-o \
		./compiled/tp5pp