tp5pp: main.cpp \
		./headers/public_or_private.hpp \
		./headers/complex.hpp \
		./headers/X.hpp \
		./headers/Y.hpp
	g++ -g ./main.cpp \
		./src/public_or_private.cpp \
		./src/complex.cpp \
		./src/X.cpp \
		./src/Y.cpp \
		-o \
		./compiled/tp5pp